version: "3.3"

services:
  web:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/packages/config/node_modules
      - /app/packages/tsconfig/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/recipes/node_modules
      - /app/apps/extension/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
