name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  CI:
    name: lint/build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: yarn --immutable

      - run: yarn codegen
        working-directory: "./apps/web"

      - run: yarn build
