name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint, test, and build apps and packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - run: yarn --immutable
      - run: yarn generate
        working-directory: "./apps/web"
      - run: yarn ci
      - run: yarn build
