name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  CI:
    name: lint/build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm i -g yarn

      - run: yarn --immutable

      - run: yarn codegen
        working-directory: "./apps/web"

      - run: yarn build
