name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint, test, and build apps and packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn --immutable
      - run: yarn generate
        working-directory: "./apps/web"
      - run: yarn ci
      - run: yarn build
