name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint, test, and build apps and packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.1

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm i --frozen-lockfile --strict-peer-dependencies
      - run: pnpm run ci
      - run: pnpm run build
