name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint, test, and build apps and packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm packages
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2.2.1
        with:
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - run: pnpm run ci
      - run: pnpm run build
