name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  CI:
    name: Lint and Build Apps and Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn --immutable

      - run: yarn codegen
        working-directory: "./apps/web"

      - run: yarn build
